language: objective-c
os: osx

env:
  global:
    - LECTURE=SWA YEAR=20
  matrix:
    - RELEASE=5.3alpha STARTRACK=true
    - RELEASE=5.3alpha STARTRACK=false
    - RELEASE=Trunk STARTRACK=true
    - RELEASE=Trunk STARTRACK=false

addons:
  homebrew:
    packages:
    - python

before_install:
  - openssl aes-256-cbc -K $encrypted_6e698d0010b7_key -iv $encrypted_6e698d0010b7_iv
    -in .encrypted.zip.enc -out .encrypted.zip -d

before_script: pip install -U pyobjc
script: bash MAKE.command
