name: tests

# Triggers the workflow on push or pull request on any branch
on: [push, pull_request]

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: macos-latest
    name: Build for Seminar Visual Abstractions
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pyobjc
      - run: bash MAKE.command
        timeout-minutes: 20
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE: trunk
          PATCH: 20582
          LECTURE: VA
          YEAR: 2022
      - uses: actions/upload-artifact@v2
        with:
          name: va2022
          path: |
            dist/VA2022.dmg
            dist/VA2022.txz
            dist/VA2022.zip
