name: tests

# Triggers the workflow on push or pull request on any branch
on:
  push:
  # pull_request:
  workflow_dispatch:
    inputs:
      lecture:
        description: "Lecture (SWA/SWT). See squeak-app release tag custom-osvm-bundle"
        required: true
        default: 'SWA'
      year:
        description: "Year (e.g. 2026)."
        required: true
        default: '2027'
      squeak-release:
        description: "Squeak release version (e.g. 6.1). Check files.squeak.org"
        required: true
        default: '6.1'
      squeak-build:
        description: "Squeak build number (e.g. 23976). Check files.squeak.org"
        required: true
        default: 23976
      osvm-build:
        description: "Build with custom-built OSVM (e.g. 202603271636). Leave empty for using current OSVM release. See squeak-app release tag custom-osvm-bundle"
        required: false # if empty, use default VM from files.squeak.org/base
        default: ''


jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: macos-14 #macos-latest
    name: Build Squeak Teaching Bundle
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
      - name: Set build parameters
        env:
          inputs: ${{ toJSON(inputs) }}
        run: ./.github/workflows/set-build-parameters.py "$inputs"
      - name: Build Image
        run: bash MAKE.command
        timeout-minutes: 30
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TERM: xterm-256
          STARTRACK: false
      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: packages ${{ matrix.star_track }}
          path: |
            ./dist/*.zip
            ./dist/*.txz
            ./dist/*.dmg
