name: tests

# Triggers the workflow on push or pull request on any branch
on: [push, pull_request, workflow_dispatch]

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: macos-14 #macos-latest
    strategy:
      matrix:
        # Create one build with StarTrack and one without (StarTrack is used to collect data for a chair's user study)
        star_track:
          - false
          - true
    name: Build with StarTrack ${{ matrix.star_track }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
      - name: Build Image
        run: bash MAKE.command
        timeout-minutes: 30
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TERM: xterm-256
          STARTRACK: ${{ matrix.star_track }}
          RELEASE: '6.0'
          PATCH: 22155
          BUNDLE_RELEASE: '6.0'
          BUNDLE_PATCH: 22155
          OSVM_BUILD: 202509300044 # Download bundle from https://github.com/squeak-smalltalk/squeak-app/releases/tag/custom-osvm-bundle
          LECTURE: SWA
          YEAR: 2025
      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: packages ${{ matrix.star_track }}
          path: |
            ./dist/*.zip
            ./dist/*.txz
            ./dist/*.dmg
